package apps.radwin.wintouch.screenManagers;

public enum HttpInterrupts
{
    ALIGNMENT_DATA,
    COURSER_LOCATION,
    BANDS_LIST,
    LINK_STATE,
    BEST_POSITION,
    EVALUATION_RESULTS,
    SET_INIT,
    FINE_ALIGNMENT,
    SET_BAND,
    SET_START_ALIGNMENT,
    SET_FINISH_ALIGNMENT,
    SET_DEREGISTER,
    SET_FINAL_DATA,
    SET_COMPLETE,
    SET_START_SYNC,
    SET_START_EVALUATION, GET_ADDRESS,
    SET_AUTH,
}
